// <auto-generated />
namespace Clinisanitas.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FixProspectCompany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixProspectCompany));
        
        string IMigrationMetadata.Id
        {
            get { return "201406131459551_FixProspectCompany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
